### ISSUE TITLE
[Question] Thickness of Eraser

### ISSUE THREAD

**Issue by yongweiy** [ddvk/remarkable-stylus#10]
I want to thank @ddvk for your amazing work. I wouldn't have got my Lamy stylus without this repo.
I notice that the original Marker Plus has a finer erasing functionality compared to that of Lamy stylus. Is this something restricted by the hardware of Lamy pen?

**Comment by dstango** [comment]
Did you manually choose the eraser from the menu and then adjust the thickness?
This is what determines the thickness of the eraser when activating it with the button.
(actually the first thing I do in a new notebook is to set the thickness to the eraser to fine...)

**Comment by yongweiy** [comment]
Oops, I didn't realize that I can choose thickness of the eraser. Shame on myself : ) Thanks for pointing that out for me!
