### ISSUE TITLE
Button question

### ISSUE THREAD

**Issue by onqun** [ddvk/remarkable-stylus#18]
is it possible to configure button to?

hold to erase
tap to undo

**Comment by dstango** [comment]
If you install the remarkable-hacks together with remarkable-stylus you get three functions:

- hold to erase
- tap to switch between the last two tools
- double-tap to undo

I think the logic for this behavior is handled in the project remarkable-hacks, as remarkable-stylus is only an utility-project with lower level functions. So if you'd like to request a change of the default behavior I'd propose to post an issue there.
