### ISSUE TITLE
Button isn't working

### ISSUE THREAD

**Issue by mslwhite3** [ddvk/remarkable-stylus#2]
I successfully installed the most recent patch using automagic. I ran the automagic for the lamy pen but it doesn't seem to be working. 

Screen output:
reMarkable: // sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-stylus/master/patch.sh -O-)"
Connecting to raw.githubusercontent.com (151.101.0.133:443)
wget: note: TLS certificate validation not implemented
-                    100% |*************************************|   540  0:00:00 ETA
Connecting to github.com (140.82.114.3:443)
wget: note: TLS certificate validation not implemented
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.217.36.220:443)
libqevdevlamyplugin. 100% |*************************************| 43080  0:00:00 ETA

**Comment by ZacharieALES** [comment]
When you say that it does not work, do you mean that the eraser is not toggled when you press on your pen button?

If you do, I think that this is normal as this patch only enables to detect when a key is pressed but it does not do anything when it happens.

If you do not, I don't know and you can ignore the following.

To toggle the eraser when the key is pressed you would also need to install the following patch by the same author:
sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" 

I don't know if the order in which these two patches are installed is important. So if it still does not work, you may have to reinstall the first patch.
