### ISSUE TITLE
Debugging?

### ISSUE THREAD

**Issue by Allaman** [ddvk/remarkable-stylus#20]
Hi,

I cant't get the erazer to work again. It used to work and I don't know what I've done to break it. Already uninstalled/reinstalled via automagic. (hacks are installed and working)
How can I debug or get a hint what is wrong?

Thanks

**Comment by ddvk** [comment]
rm1 with staedler or lamy?

**Comment by Allaman** [comment]
sry, RM2 with 2.14 and lamy

**Comment by Allaman** [comment]
anybody? :(

**Comment by dstango** [comment]
My Lamy's button stopped working about a month ago. It was a hardware failure - the button was not pressable any more. I needed to get a new pen to fix the issue.

So my suggestion: try either your Lamy with a different device or your rm with a different pen to sort out hardware issues first.

**Comment by Allaman** [comment]
thanks for your hint although this would be hilarious. The pen was not even a month old...

I guess I have to accept the current state as I do not have any other hardware to test this

**Comment by Allaman** [comment]
I came across [RemarkableLamyEraser](https://github.com/isaacwisdom/RemarkableLamyEraser) and with this service it is working! No HW issue
