### ISSUE TITLE
Any idea if this is safe on rM 3.0 Beta?

### ISSUE THREAD

**Issue by brandonkboswell** [ddvk/remarkable-stylus#23]
My guess is it likely is, but I don't want to brick my device by being too hasty. Any idea?

**Comment by dstango** [comment]
As it's on the OS level I'd guess there shouldn't be interference with xochitl which is an application.
Yet you probably wouldn't get any benefit from it without the rm-hacks installed, and they are not available yet for rm (xochitl) softare 3.0.
So what's your use case?

**Comment by brandonkboswell** [comment]
@dstango I didn't realize that rm-hacks is required this to work. My use case was to try to get my eraser button back working while I wait for rm-hacks, but it sounds like I need to hold tight.

**Comment by dstango** [comment]
Do you have an rm1 or rm2 device? AFAIK the rm1 only supports the Lamy eraser button with the rm hacks -- it's more an add-on to the rm-hacks.
I'm not sure about the rm2 though: as the rm2 supports the stylus with the "rubber side", the situation might be different, as I guess the rubber side of the rm stylus and the Lamy button technically speaking create the same or similar signal for the tablet.

Anyhow: as this project makes the OS of the tablet receive a "key press" event, other software out in the wild might benefit from it, too.

**Comment by khorinisgefasel** [comment]
Maybe you could already try [this one](https://github.com/isaacwisdom/RemarkableLamyEraser), might work ..

**Comment by brandonkboswell** [comment]
@khorinisgefasel Yes, Isaac's repo works well with reMarkable 3.0.

**Comment by Eeems** [comment]
As part of the [EULA](https://support.remarkable.com/s/article/End-user-agreement-for-Opt-In-Beta) you agree to in order to be able to install the beta, you agree that you will not install third party software on the device. I would recommend sticking to only using this on stable releases.

@ddvk it might be worth closing this issue now.
