### ISSUE TITLE
Is it possible to distinguish between distinct pens?

### ISSUE THREAD

**Issue by AdamSLevy** [ddvk/remarkable-stylus#5]
I own several pens compatible with the remarkable 1:
- remarkable
- Staedtler noris digital
- Lamy digital

I was wondering if there is any way to distinguish these pens, or even two pens of the same model, in software. If not, oh well. But if so, it'd be really cool to be able to tie certain pens with certain writing implements in xochitl or other software.

Is this at all possible?

**Comment by ddvk** [comment]
nope, not technically possible (as far as I know how wacom/emr works no such data gets send)
